// Ce projet est un site ODAM STORE complet en Next.js // Frontend + Backend pour paiement Mashapay / CinetPay / Stripe

// Structure du projet : // /pages/index.js       ← frontend boutique // /pages/api/create-payment.js   ← backend paiement

// pages/index.js import { useState } from 'react';

const products = [ { id: 1, name: "Dell XPS 13 Laptop", price: 1200 }, { id: 2, name: "HP EliteBook", price: 1100 }, { id: 3, name: "Lenovo ThinkPad", price: 1050 }, { id: 4, name: "MacBook Pro", price: 2500 }, { id: 5, name: "Acer Aspire 5", price: 800 }, { id: 6, name: "Asus ZenBook", price: 1400 }, { id: 7, name: "Microsoft Surface Laptop", price: 1500 }, { id: 8, name: "Samsung Galaxy Book", price: 1300 }, { id: 9, name: "HP Office Printer", price: 600 }, { id: 10, name: "Canon Wireless Printer", price: 750 }, { id: 11, name: "Office Desk", price: 900 }, { id: 12, name: "Executive Office Chair", price: 650 }, { id: 13, name: "Office Cabinet", price: 700 }, { id: 14, name: "Document Scanner", price: 550 }, { id: 15, name: "Office Monitor 27 inch", price: 520 }, { id: 16, name: "Dual Monitor Setup", price: 1000 }, { id: 17, name: "Laptop Docking Station", price: 510 }, { id: 18, name: "External SSD 2TB", price: 530 }, { id: 19, name: "Conference Webcam", price: 540 }, { id: 20, name: "Office Projector", price: 1200 }, { id: 21, name: "Office Router Pro", price: 560 }, { id: 22, name: "Network Switch", price: 580 }, { id: 23, name: "Laptop Backpack", price: 500 }, { id: 24, name: "Office Paper Pack", price: 520 }, { id: 25, name: "Office Keyboard", price: 510 }, { id: 26, name: "Office Mouse", price: 505 }, { id: 27, name: "Standing Desk", price: 1500 }, { id: 28, name: "Meeting Table", price: 2000 }, { id: 29, name: "Large Office Cabinet", price: 1800 }, { id: 30, name: "Business Laptop Bundle", price: 3000 }, { id: 31, name: "Complete Office Setup", price: 5000 } ];

export default function Home() { const [cart, setCart] = useState([]); const [loading, setLoading] = useState(false);

const addToCart = (product) => setCart([...cart, product]); const total = cart.reduce((t, p) => t + p.price, 0);

const checkout = async () => { if(cart.length === 0) return alert('Cart is empty'); setLoading(true); try { const res = await fetch('/api/create-payment', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ amount: total, currency: 'USD', description: 'ODAM STORE Purchase' }) }); const data = await res.json(); if(data.payment_url) window.location.href = data.payment_url; else alert('Payment link error'); } catch(e) { alert('Payment error'); console.error(e); } setLoading(false); };

return ( <div className='p-6 max-w-7xl mx-auto'> <h1 className='text-4xl font-bold mb-6'>ODAM STORE</h1> <div className='grid grid-cols-1 md:grid-cols-3 gap-6'> {products.map(p => ( <div key={p.id} className='border rounded-2xl p-4 shadow'> <h2 className='text-xl font-semibold'>{p.name}</h2> <p className='text-lg mt-2 font-bold'>${p.price}</p> <button onClick={() => addToCart(p)} className='mt-4 bg-black text-white px-4 py-2 rounded-xl'>Add to cart</button> </div> ))} </div> <div className='mt-10 border-t pt-6'> <h2 className='text-2xl font-bold'>Cart ({cart.length})</h2> <p className='mt-2 text-lg'>Total: ${total}</p> <button onClick={checkout} disabled={loading} className='mt-4 bg-green-600 text-white px-6 py-3 rounded-xl'> {loading ? 'Processing...' : 'Checkout'} </button> </div> </div> ); }

// pages/api/create-payment.js /* export default async function handler(req, res) { const response = await fetch('https://api.mashapay.com/create-payment', { method: 'POST', headers: { 'Authorization': Bearer ${process.env.PAYMENT_SECRET_KEY}, 'Content-Type': 'application/json' }, body: JSON.stringify(req.body) }); const data = await response.json(); res.status(200).json(data); } */
